```{r warning=FALSE}
library(lme4)
library(lmerTest)
library(magrittr)
library(dplyr)
library(ggeffects)
library(ggplot2)
library(ggplot2)
library(cowplot)
```

# Data Clean

```{r}
data=read.csv(file='data/Data for R.csv')
```

```{r}
data2=read.csv(file='data/Less Data for R.csv')
```

```{r}
data$Participant_number <- as.factor(data$Participant_number)
data$Side<- as.factor(data$Side)
data$Previous_Side<- as.factor(data$Previous_Side)
```

```{r}
#data2$Chose_priority <- as.factor(data2$Chose_priority)
data2$Participant_number <- as.factor(data2$Participant_number)
data2$Side<- as.factor(data2$Side)
data2$Previous_Side<- as.factor(data2$Previous_Side)
```

# Analysis

### no extra values

```{r warning=FALSE}
prio <- glmer(Chose_priority ~ 1 + (1 | Participant_number), 
              data, family=binomial)
summary(prio)
exp(confint(prio))
sum = data %>% group_by(Participant_number) %>% 
  summarise(p_dominant=mean(Chose_priority))
```

```{r}
hist(sum$p_dominant, 
     main="Ratio of Choosing Priority Stimulus Across Participants", 
     xlab="Ratio of Choosing Priority Stimulus", 
     ylab="Frequency Across Participants")
```

### no extra values filtered

```{r}
prio2 <- glmer(Chose_priority ~ 1 + (1 | Participant_number), 
               data2, family=binomial)
summary(prio2)
exp(confint(prio2))
sum = data2 %>% group_by(Participant_number) %>% 
  summarise(p_dominant2=mean(Chose_priority))
```

```{r}
hist(sum$p_dominant2, 
     main="Ratio of Choosing Priority Stimulus Across Participants", 
     xlab="Ratio of Choosing Priority Stimulus", 
     ylab="Frequency Across Participants")
```

### interaction

```{r}
inter <- glmer(Chose_priority ~ scale(Priority_difference) * 
                 scale(dominant_priority) + (1 | Participant_number), 
               data, family=binomial)
summary(inter)
```

# Plot

```{r}
ggpredictions = data.frame(ggpredict(inter, terms = c("Priority_difference[n=3]","dominant_priority[n=3]")))
colnames(ggpredictions)[1]="Priority_difference"
colnames(ggpredictions)[6]="dominant_priority"
ggplot(ggpredictions, aes(x = dominant_priority, y = predicted)) +
  geom_line(aes(color=Priority_difference)) +
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high),alpha=0.2) +
  theme_classic() + labs(x="Priority Difference", y="How much it predicts choosing the priority stimulus", title="Priority Difference*Dominant Stimulus Priority in predicting choosing the dominant stimulus", color="Dominant Stimulus' Priority")
```

```{r}
#interaction filtered
inter2<-glmer(Chose_priority~scale(Priority_difference)*scale(dominant_priority)+(1|Participant_number),data2,family=binomial)
summary(inter2)

ggpredictions = data.frame(ggpredict(inter2, terms = c("Priority_difference[all]","dominant_priority")))
colnames(ggpredictions)[1]="Priority_difference"
colnames(ggpredictions)[6]="dominant_priority"
ggplot(ggpredictions, aes(x = Priority_difference, y = predicted)) +
  geom_line(aes(color=dominant_priority)) +
  geom_ribbon(aes(fill=dominant_priority,ymin = conf.low, ymax = conf.high),alpha=0.2) +
  theme_classic() + labs(x="Priority Difference", y="How much it predicts choosing the priority stimulus", title="Priority Difference*Dominant Stimulus Priority in predicting choosing the dominant stimulus", color="Dominant Stimulus' Priority")
dif<-glmer(Chose_priority~scale(dominant_priority)+(1|Participant_number),data2,family=binomial)
pri<-glmer(Chose_priority~scale(dominant_priority)+(1|Participant_number),data,family=binomial)
summary(pri)
summary(dif)
exp(confint(dif))
exp(confint(pri))
y=anova(inter, pri)
y
```

```{r}
ggpredictions2 = data.frame(ggpredict(dif, terms = c("Priority_difference")))
colnames(ggpredictions2)[1]="Priority_difference"
#colnames(ggpredictions)[6]="dominant_priority"
ggplot(ggpredictions2, aes(x = Priority_difference, y = predicted)) +
  geom_line(aes(color="red1")) +
  geom_point()+geom_smooth(method="lm") +
  #geom_ribbon(aes(fill=Priority_difference,ymin = conf.low, ymax = conf.high),alpha=0.2) +
  theme_classic() + labs(x="Priority Difference", y="How much it predicts choosing the priority stimulus", title="Priority Difference and Choosing the Dominant Stimulus")
```

```{r}
predicted.data <-data.frame(probability.of.pr=dif$fitted.values, pr=data2$Chose_priority, dif2=data2$Priority_difference)
predicted.data <- predicted.data[order(predicted.data$probability.of.pr, decreasing=FALSE),]
ggplot(data=predicted.data, aes(x=dif2, y=probability.of.pr)) + geom_point(aes(color=pr), alpha=1, shape=4, stroke=2) + xlab("Priority Difference") + ylab("predicted probability to choose priority stimulus")
```

### side

```{r}
side<-glmer(Side~Previous_Side+(1|Participant_number),data,family=binomial)
exp(confint(side))
summary(side)
summary(bigmixed)
exp(confint(m))
```

### rt

```{r}
rtm=lmer(rt~scale(Priority_difference)*scale(dominant_priority)+Chose_priority+scale(chosen_pr)+(1|Participant_number),data)
summary(rtm)
rtm2=lmer(rt~scale(dominant_priority)+(1|Participant_number),data)
summary(rtm2)
rtm3=lmer(rt~scale(Priority_difference)+(1|Participant_number),data)
summary(rtm3)
rtm4=lmer(rt~Chose_priority+(1|Participant_number),data)
summary(rtm4)
rtm5=lmer(rt~scale(chosen_pr)+(1|Participant_number),data)
summary(rtm5)
```

### Old

```{r}
logistic <-glm(Chose_priority ~ Priority_difference, data=data, family="binomial")
summary(logistic) #p=.145
ll.null <- logistic$null.deviance/-2
ll.proposed <- logistic$deviance/-2
rsq = (ll.null -ll.proposed) / ll.null
rsq #0.00026
1-pchisq(2*(ll.proposed - ll.null), df=(length(logistic$coefficients)-1)) #0.145
```

```{r}
rtanova=aov(chosen_pr ~ rt, data = data)
summary (rtanova)
```

```{r}
logistic2 <-glm(Chose_priority ~ Priority_difference*dominant_priority, data=data, family="binomial")
summary(logistic2) #p=0.00000272 dominant_priority; 0.0042 Priority_difference:dominant_priority
ll.null2 <- logistic2$null.deviance/-2
ll.proposed2 <- logistic2$deviance/-2
rsq2 = (ll.null2 - ll.proposed2) / ll.null2
rsq2 # 0.00345
1-pchisq(2*(ll.proposed2 - ll.null2), df=(length(logistic2$coefficients)-1)) #0.0000035
```

```{r}
logistic3 <-glm(Chose_priority ~ Priority_difference*Participant_number, data=data, family="binomial")
summary(logistic3) #intercept p=0.391; no other significant p.
ll.null3 <- logistic3$null.deviance/-2
ll.proposed3 <- logistic3$deviance/-2
rsq3 = (ll.null3 - ll.proposed3) / ll.null3
rsq3 #0.0006
1-pchisq(2*(ll.proposed3 - ll.null3), df=(length(logistic3$coefficients)-1)) #p=0.181
```

```{r}
logistic4 <-glm(Chose_priority ~ dominant_priority, data=data, family="binomial")
summary(logistic4) #intercept p=0.00000000000098
ll.null4 <- logistic4$null.deviance/-2
ll.proposed4 <- logistic4$deviance/-2
rsq4 = (ll.null4 - ll.proposed4) / ll.null4
rsq4 #0.000967
1-pchisq(2*(ll.proposed4 - ll.null4), df=(length(logistic4$coefficients)-1)) #p=0.005
```

```{r}
logistic5 <-glm(Chose_priority ~ dominant_priority*Priority_difference*Participant_number, data=data, family="binomial")
summary(logistic5) #intercept p=0.00000000000098
ll.null5 <- logistic5$null.deviance/-2
ll.proposed5 <- logistic5$deviance/-2
rsq5 = (ll.null5 - ll.proposed5) / ll.null5
rsq5 #0.00403
1-pchisq(2*(ll.proposed5 - ll.null5), df=(length(logistic5$coefficients)-1)) #p=0.005
```

```{r}
logrt <-glm(Chose_priority ~ rt, data=data, family="binomial")
summary(logrt) #intercept p=0.00000000000098
ll.nullrt <- logrt$null.deviance/-2
ll.proposedrt <- logrt$deviance/-2
rsqrt = (ll.nullrt - ll.proposedrt) / ll.nullrt
rsqrt #0.0000019
1-pchisq(2*(ll.proposedrt - ll.nullrt), df=(length(logrt$coefficients)-1)) #p=0.85
```

```{r}
sidelog<-glm(Side ~ Previous_Side, data=data, family="binomial")
summary(sidelog) #p<2e-16
ll.nullside <- sidelog$null.deviance/-2
ll.proposedside <- sidelog$deviance/-2
rsqside = (ll.nullside -ll.proposedside) / ll.nullside
rsqside #0.0174
1-pchisq(2*(ll.proposedside - ll.nullside), df=(length(sidelog$coefficients)-1)) #0
```

### dif

```{r}
predicted.data <-data.frame(probability.of.pr=logistic$fitted.values, 
                            pr=data$Chose_priority, 
                            dif=data$Priority_difference)
predicted.data <- predicted.data[order(predicted.data$probability.of.pr, 
                                       decreasing=FALSE),]
ggplot(data=predicted.data, aes(x=dif, y=probability.of.pr)) + 
  geom_point(aes(color=pr), alpha=1, shape=4, stroke=2) + 
  xlab("Priority Difference") + 
  ylab("predicted probability to choose priority")
```

### dom

```{r}
predicted.data <-data.frame(probability.of.pr=logistic4$fitted.values, pr=data$Chose_priority, dom=data$dominant_priority*-1)
predicted.data <- predicted.data[order(predicted.data$probability.of.pr, decreasing=FALSE),]
ggplot(data=predicted.data, aes(x=dom, y=probability.of.pr)) + geom_point(aes(color=pr), alpha=1, shape=4, stroke=2) + xlab("Dominant") + ylab("predicted probability to choose priority")
```

### sidetoside

```{r}
predicted.data <-data.frame(probability.of.side=sidelog$fitted.values, chside=data$Side, dom=data$dominant_priority*-1)
predicted.data <- predicted.data[order(predicted.data$probability.of.side, decreasing=FALSE),]
ggplot(data=predicted.data, aes(x=dom, y=probability.of.pr)) + geom_point(aes(color=pr), alpha=1, shape=4, stroke=2) + xlab("Dominant") + ylab("predicted probability to choose priority")
```


